### ISSUE TITLE
Замахав вже зі сповіщенннями про апдейти.

### ISSUE THREAD

**Issue by slado122** [nacknime-official/gdz_ukraine#2]
Спамити повідомленнями про те, як змінилися назви змінних в коді - тупо і не має сенсу. Краще зроби спеціальний канал з апдейтами, куди будуть приходити тільки люди з бажанням. А так, бот класний.

**Comment by nacknime-official** [comment]
Привет. Спасибо за issue.
Идея хорошая, займусь этим в ближайшее время.

**Comment by nacknime-official** [comment]
Теперь уведомления о новых версиях будут приходить в https://t.me/gdz_ukraine_updates.
